## Default dimension shaders
## There only 3 main dimension shaders:
## - The Overworld used for all dimensions by default
## - The Nether where it is devoid of sunlight
## - The End where it involves a black hole

## For the most part, modded dimensions use either the first 2 and rarely the latter depending on the theme of the dimension

# The Overworld
    dimension.world0 = *
# The Nether
    dimension.world-1 = minecraft:the_nether minecraft:nether \
        undergarden:undergarden
# Dimensional Doors
    dimension.world-2 = dimdoors:public_pockets dimdoors:dungeon_pockets
    dimension.world-3 = dimdoors:limbo
    dimension.world-4 = dimdoors:personal_pockets
# The End
    dimension.world1 = minecraft:the_end minecraft:end
