"""
Runtime definitions and constants injected by Iris and Distant Horizons.
Separated to keep linter modules focused and concise (SRP).
"""

IRIS_DH_BUILTINS_VERT = """
#ifndef MC_BUILTINS_INJECTED
#define MC_BUILTINS_INJECTED
#define MC_RENDER_STAGE_NONE 0
#define MC_RENDER_STAGE_SKY 1
#define MC_RENDER_STAGE_SUN 2
#define MC_RENDER_STAGE_MOON 3
#define MC_RENDER_STAGE_STARS 4
#define MC_RENDER_STAGE_VOID 5
#define MC_RENDER_STAGE_TERRAIN_SOLID 6
#define MC_RENDER_STAGE_TERRAIN_CUTOUT_MIPPED 7
#define MC_RENDER_STAGE_TERRAIN_CUTOUT 8
#define MC_RENDER_STAGE_ENTITIES 9
#define MC_RENDER_STAGE_BLOCK_ENTITIES 10
#define MC_RENDER_STAGE_DESTROY 11
#define MC_RENDER_STAGE_OUTLINE 12
#define MC_RENDER_STAGE_DEBUG 13
#define MC_RENDER_STAGE_HAND_SOLID 14
#define MC_RENDER_STAGE_TERRAIN_TRANSLUCENT 15
#define MC_RENDER_STAGE_TRIPWIRE 16
#define MC_RENDER_STAGE_PARTICLES 17
#define MC_RENDER_STAGE_CLOUDS 18
#define MC_RENDER_STAGE_RAIN_SNOW 19
#define MC_RENDER_STAGE_WORLD_BORDER 20
#define MC_RENDER_STAGE_HAND_TRANSLUCENT 21
#define DH_BLOCK_UNKNOWN 0
#define DH_BLOCK_AIR 1
#define DH_BLOCK_WATER 2
#define DH_BLOCK_LAVA 3
#define DH_BLOCK_SOLID 4
#define DH_BLOCK_ILLUMINATED 5
#define DH_BLOCK_LEAVES 6
attribute int dhMaterialId;
#endif
"""

IRIS_DH_BUILTINS_FRAG = """
#ifndef MC_BUILTINS_INJECTED
#define MC_BUILTINS_INJECTED
#define MC_RENDER_STAGE_NONE 0
#define MC_RENDER_STAGE_SKY 1
#define MC_RENDER_STAGE_SUN 2
#define MC_RENDER_STAGE_MOON 3
#define MC_RENDER_STAGE_STARS 4
#define MC_RENDER_STAGE_VOID 5
#define MC_RENDER_STAGE_TERRAIN_SOLID 6
#define MC_RENDER_STAGE_TERRAIN_CUTOUT_MIPPED 7
#define MC_RENDER_STAGE_TERRAIN_CUTOUT 8
#define MC_RENDER_STAGE_ENTITIES 9
#define MC_RENDER_STAGE_BLOCK_ENTITIES 10
#define MC_RENDER_STAGE_DESTROY 11
#define MC_RENDER_STAGE_OUTLINE 12
#define MC_RENDER_STAGE_DEBUG 13
#define MC_RENDER_STAGE_HAND_SOLID 14
#define MC_RENDER_STAGE_TERRAIN_TRANSLUCENT 15
#define MC_RENDER_STAGE_TRIPWIRE 16
#define MC_RENDER_STAGE_PARTICLES 17
#define MC_RENDER_STAGE_CLOUDS 18
#define MC_RENDER_STAGE_RAIN_SNOW 19
#define MC_RENDER_STAGE_WORLD_BORDER 20
#define MC_RENDER_STAGE_HAND_TRANSLUCENT 21
#define DH_BLOCK_UNKNOWN 0
#define DH_BLOCK_AIR 1
#define DH_BLOCK_WATER 2
#define DH_BLOCK_LAVA 3
#define DH_BLOCK_SOLID 4
#define DH_BLOCK_ILLUMINATED 5
#define DH_BLOCK_LEAVES 6
#endif
"""
